spring:
  datasource:
    url: jdbc:postgresql://costumer-db:5432/costumerdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
